# Generated by Django 2.1.3 on 2018-12-03 08:16

from django.db import migrations, models
import django.db.models.deletion
import things.directionOfFile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sections', models.PositiveSmallIntegerField(choices=[(1, 'finance'), (2, 'marketing'), (3, 'analyze'), (4, 'Calculation'), (5, 'Theory')])),
                ('question', models.TextField(default='')),
                ('img', models.ImageField(blank=True, default='', upload_to=things.directionOfFile.images_upload)),
                ('second_part', models.TextField(blank=True, default='')),
                ('A', models.CharField(max_length=256)),
                ('B', models.CharField(max_length=256)),
                ('C', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('user', models.CharField(blank=True, default='', max_length=256, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('university', models.CharField(max_length=256)),
                ('speciality', models.CharField(max_length=256)),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='things.User1')),
            ],
        ),
        migrations.CreateModel(
            name='User3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='things.User1')),
            ],
        ),
    ]
