# Generated by Django 2.1.3 on 2018-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
