# Generated by Django 2.1.3 on 2018-12-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='user',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='things.User1'),
        ),
    ]
