# Generated by Django 2.1.3 on 2018-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_auto_20181211_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sections',
            field=models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'Russion')]),
        ),
    ]
