# Generated by Django 2.1.3 on 2018-12-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_auto_20181218_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
