# Generated by Django 2.1.3 on 2018-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_auto_20181219_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='score',
            field=models.IntegerField(blank=True, default='-', null=True),
        ),
    ]
